### ISSUE TITLE
Задача 1 для занятия 3

### ISSUE THREAD

**Issue by natasha08n** [VovaMelnyk/React-tasks#2]
В макете-шаблоне нет реализованного варианта с формой добавления города. Предлагаю добавить, чтобы можно было студентам на первом занятии показать рабочий вариант, что мы реализуем за весь курс.

P. S. Вова, спасибо за задания, буду применять с сегодняшнего урока этот шаблон)

**Comment by VovaMelnyk** [comment]
[PR](https://github.com/VovaMelnyk/React-tasks/pull/4)
